# Generated by Django 3.2.3 on 2021-05-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20210528_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(auto_now_add=True, help_text='Если нет даты, то заполняется автоматически', null=True, verbose_name='Дата'),
        ),
    ]
