# Generated by Django 3.2.3 on 2021-05-31 21:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0011_auto_20210531_2221'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likebookuser',
            unique_together={('book', 'user')},
        ),
    ]
