# Generated by Django 3.2.3 on 2021-06-03 16:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0016_alter_likebookuser_rate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likebookuser',
            unique_together={('book', 'user', 'rate')},
        ),
    ]
