# Generated by Django 3.2.3 on 2021-06-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_alter_likebookuser_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likebookuser',
            name='rate',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
