# Generated by Django 3.2.3 on 2021-06-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0021_alter_book_total_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='total_stars',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
