# Generated by Django 3.2.3 on 2021-06-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0026_testmodelbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodelbook',
            name='slug',
            field=models.SlugField(auto_created=True, blank=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
