# Generated by Django 3.2.3 on 2021-06-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0028_delete_testmodelbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
