# Generated by Django 3.2.3 on 2021-06-07 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0031_testcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcomment',
            name='test',
            field=models.ForeignKey(db_column='title', on_delete=django.db.models.deletion.CASCADE, to='manager.testtable'),
        ),
    ]
