# Generated by Django 3.2.3 on 2021-06-10 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0034_tmpbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='likebookuser',
            name='tmp_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tmp_book_likes', to='manager.tmpbook'),
        ),
    ]
