# Generated by Django 3.2.3 on 2021-06-10 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0037_tmpbook_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likebookuser',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_likes', to='manager.book'),
        ),
    ]
