# Generated by Django 3.2.3 on 2021-06-21 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0050_alter_tableaggregate_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TableAggregate',
        ),
    ]
