# Generated by Django 3.2.3 on 2021-06-25 09:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0054_shoppingbasketuser_customer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shoppingbasketuser',
            unique_together={('customer',)},
        ),
        migrations.RemoveField(
            model_name='shoppingbasketuser',
            name='user',
        ),
    ]
