# Generated by Django 3.2.3 on 2021-06-25 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0055_auto_20210625_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_to_read', to='manager.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_in_read', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
