# Generated by Django 3.2.3 on 2021-05-29 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(auto_now_add=True, help_text='Если нет даты, то заполняется автоматически', null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(default='Book description to be added soon', null=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.book')),
            ],
        ),
    ]
