# Generated by Django 3.2.3 on 2021-06-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_auto_20210603_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likebookuser',
            name='rate',
            field=models.FloatField(null=True),
        ),
    ]
