# Generated by Django 3.2.3 on 2021-06-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_alter_likebookuser_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likebookuser',
            name='rate',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
