# Generated by Django 3.2.3 on 2021-06-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0020_book_total_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='total_stars',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
