# Generated by Django 3.2.3 on 2021-06-07 08:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0025_alter_book_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModelBook',
            fields=[
                ('slug', models.SlugField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(help_text='ну это типа название книги', max_length=50, verbose_name='Наименование')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Если нет даты, то заполняется автоматически', null=True, verbose_name='Дата')),
                ('description', models.TextField(default='Book description to be added soon', null=True)),
                ('likes', models.PositiveIntegerField(default=0, null=True)),
                ('rating', models.FloatField(default=5.0, null=True)),
                ('total_stars', models.PositiveIntegerField(default=0, null=True)),
                ('authors', models.ManyToManyField(related_name='test_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'книга',
                'verbose_name_plural': 'книги',
            },
        ),
    ]
