# Generated by Django 3.2.3 on 2021-06-07 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0027_alter_testmodelbook_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModelBook',
        ),
    ]
