# Generated by Django 3.2.3 on 2021-06-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0029_alter_book_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
