# Generated by Django 3.2.3 on 2021-06-10 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0035_likebookuser_tmp_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestComment',
        ),
        migrations.DeleteModel(
            name='TestTable',
        ),
    ]
