# Generated by Django 3.2.3 on 2021-06-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0043_auto_20210610_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmpbook',
            name='id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
