# Generated by Django 3.2.3 on 2021-06-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0044_alter_tmpbook_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmpbook',
            name='id',
            field=models.PositiveIntegerField(auto_created=True, blank=True, null=True),
        ),
    ]
